pool:
   vmImage: 'macOS 10.13'
   
trigger:
  branches:
    include:
      - develop

steps:
- script: |
    sudo xcode-select -switch /Applications/Xcode_10.app
    fastlane prepare 
  env:
    GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)   
  displayName: "Setup environment"

- script: |
    fastlane build
  displayName: "Build"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "build"
    artifactName: "Build logs"
  condition: succeededOrFailed()
  displayName: "Store build log"

- script: |
    fastlane test
  displayName: "Test"

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'test/*.junit'
  condition: succeededOrFailed()
  displayName: "Publish test results"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "SnapshotResults"
    artifactName: "Snapshot failures"
  condition: failed()
  displayName: "Store failed snapshots"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "test"
    artifactName: "Test logs"
  condition: succeededOrFailed()
  displayName: "Store test log"

- script: |
    fastlane post_test
  env:  
    CODECOV_TOKEN: $(CODECOV_TOKEN)
    DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master"
    GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)   
  displayName: "Post Test"
