defaults: &defaults
  environment:
    - DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/fix/xcode-9.3"
  macos:
    xcode: "9.3.0"
  shell: /bin/bash --login -eo pipefail

# ----------------CACHING----------------

# Gems
gems_cache: &gems_cache
  key: v4-{{ checksum "Gemfile.lock" }}
  paths: ~/.gem

# Carthage
carthage_cache: &carthage_cache
  key: v2-{{ checksum "Cartfile.resolved" }}
  paths: Carthage/Build

# DerivedData
buildfiles_cache: &buildfiles_cache
  key: v2-{{ .Revision }}
  paths: DerivedData

# ------------Environment-----------------
setup_environment: &setup_environment
  name: "Setup environment"
  command: |
    mkdir -p build
    curl -O "${DEPENDENCIES_BASE_URL}/environment.sh"
    bash environment.sh

version: 2
jobs:
      
  build:
    <<: *defaults
    steps:
    - checkout
    - run: *setup_environment
    - restore_cache: *gems_cache
    - restore_cache: *carthage_cache
    - run: 
        name: "Get dependencies"
        command: bash dependencies.sh
    - run: 
        name: "Build"
        command: bash build.sh
    - save_cache: *gems_cache
    - save_cache: *carthage_cache
    - persist_to_workspace:
        root: .
        paths: 
          - DerivedData
          - build

  test:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: *setup_environment
    - restore_cache: *gems_cache
    - restore_cache: *carthage_cache
    - run: 
        name: "Test"
        command: bash test.sh
    - run: 
        name: "Post test"
        command: bash post_test.sh
    - store_artifacts:
        path: SnapshotResults
    - store_test_results:
        path: build/junit


# ----------------WORKFLOWS----------------
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
