name: C1 C2 C3 Production

on: 
  workflow_dispatch:
    inputs:
      column:
        description: 'Column (C1, C2, C3, all)'
        type: choice
        options:
          - C1
          - C2
          - C3
          - all
        required: true
        default: 'all'

permissions: 
  checks: write

jobs:
  column_1_production:
    if: ${{ inputs.column == 'C1' || inputs.column == 'all' }}
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      fastlane_action: appstore_col_1_prod
      is_cloud_build: false
      skip_security_tests: false
    secrets: inherit


  column_2_production:
    if: ${{ inputs.column == 'C2' || inputs.column == 'all' }}
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      fastlane_action: appstore_col_2_prod
      is_cloud_build: false
      skip_security_tests: false
    secrets: inherit
  
  column_3_production:
    if: ${{ inputs.column == 'C3' || inputs.column == 'all' }}
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      fastlane_action: appstore_col_3_prod
      is_cloud_build: false
      skip_security_tests: false
    secrets: inherit
