name: Run Carthage update, then create Bump Pull Request

on:
  workflow_dispatch:

jobs:
  create-bump-pr:
    runs-on: macos-10.15

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create bump PR
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            bash <(curl --silent https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Scripts/createBumpPR.sh)
