name: iOS 14.4 Simulator Test

on: 
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  Run_Tests_Xcode_13_1_iOS_14_4:
    runs-on: macos-11
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.1.app && /usr/bin/xcodebuild -version

    - name: Carthage
      env:
        GITHUB_TOKEN: ${{ secrets.DISPATCH_SECRET }}
      run: carthage bootstrap --platform ios --use-xcframeworks

    - name: Link to 14.4 Simulators
      run: |
        echo "Creating Runtimes folder if needed..."
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        echo "Creating symlink of the iOS 14.4 runtime..."
        sudo ln -s /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.4.simruntime

    - name: Run tests
      run: |
        xcodebuild test -scheme WireSyncEngine -project WireSyncEngine.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4' \
        -retry-tests-on-failure| xcpretty && exit ${PIPESTATUS[0]}
