name: dispatch to downstream repos for new release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'
    
jobs:
  dispatch:
    runs-on: ubuntu-20.04

    steps:
      - name: dispatch to downstream repos when this repo released a new version
        run: |
          curl -X POST https://api.github.com/repos/wireapp/wire-ios/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{ secrets.DISPATCH_SECRET }} \
          --data '{"event_type": "newRelease", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
