name: dispatch to download stream repos for new release

on:
  workflow_dispatch:
  release:
    type: [ published ]

jobs:
  dispatch:
    runs-on: ubuntu-20.04

    steps:
      - name: tell downstream(s) repo this repo published a new release
        run: |
          curl -X POST https://api.github.com/repos/wireapp/wire-ios/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{ secrets.DISPATCH_SECRET }} \
          --data '{"event_type": "newRelease", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
