name: SwiftLint

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
  merge_group:
    types: [checks_requested]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    if: >
    github.event.action != 'edited' || (
      github.event.changes.title == null &&
      github.event.changes.body == null &&
      github.event.changes.assignees == null &&
      github.event.changes.reviewers == null &&
      github.event.changes.labels == null
    )
    container:
      image: ghcr.io/realm/swiftlint:0.55.1

    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        run: |
          swiftlint --reporter github-actions-logging --strict --quiet
