name: SwiftFormat

on:
  pull_request:
  merge_group:
    types: [checks_requested]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftFormat:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    container:
      image: ghcr.io/nicklockwood/swiftformat:0.54.0

    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftFormat
        run: >
          swiftformat --lint
          ./SourceryPlugin
          ./WireAPI
          ./WireAnalytics
          ./WireDomain
          ./WireFoundation
          ./WireUI
          ./scripts
          --reporter github-actions-log
          --config .swiftformat
