name: iOS 15 Simulator Test

on: 
  workflow_dispatch:
jobs:
  Run_Tests_Xcode_12_4_iOS_15:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app && /usr/bin/xcodebuild -version

#     - name: Download all workflow run artifacts
#       uses: actions/download-artifact@v2
#       with:
#         name: carthage-artifact
#         path: Carthage/
      
    - name: Carthage
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash setup.sh

      
    - name: Archive Carthage artifacts
      uses: actions/upload-artifact@v2
      with:
          name: carthage-artifact
          path: Carthage/

#     - name: Link to 15.0 Simulators
#       run: |
#         echo "Creating Runtimes folder if needed..."
#         sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
#         echo "Creating symlink of the iOS 15.0 runtime..."
#         echo "ls Xcode path"
#         ls -n /Applications/ | grep Xcode*
#         sudo ln -s /Applications/Xcode_13.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 15.0.simruntime

    - name: Run tests
      run: xcodebuild test -scheme Wire-iOS -project Wire-iOS.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}
