name: Xcode 13 iOS 15 Simulator Test

on: 
  workflow_dispatch:
jobs:
  Run_Tests_Xcode_12_4_iOS_14_4:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
      
    - name: Carthage
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash setup.sh

    - name: Run tests
      run: xcodebuild test -scheme Wire-iOS -project Wire-iOS.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}
